# Generated by Django 3.2 on 2021-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterservice', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['entry_id'], name='Favorite_entry_i_7df575_idx'),
        ),
    ]
